import Link from "next/link";
import { BolyMessage } from "@/components/BolyCompanion";
import { Curriculum } from "@/components/Curriculum";
import { Section } from "@/components/Section";
import { bolilloCourse } from "@/content/bolillo-course";

export default function PremiumBolilloPage() {
  return <><Section eyebrow="Curso Maestro de Bolillo" title="Versión Premium: experiencia completa con acompañamiento"><div className="grid gap-8 lg:grid-cols-[1.15fr_0.85fr]"><div className="space-y-6 text-lg leading-8"><p>La versión premium reúne los 14 módulos reales del Curso Maestro de Bolillo con videos QR preparados, recursos por módulo, fotografías técnicas planificadas y acompañamiento contextual de Boly™.</p><p>Autor: <strong className="text-coral">{bolilloCourse.author}</strong>.</p><blockquote className="border-l-4 border-coral pl-5 font-display text-2xl text-toast">“{bolilloCourse.quotes[0]}”</blockquote><Link href="/contacto" className="btn-primary">Explorar el programa</Link></div><div className="soft-card p-8"><h3 className="font-display text-2xl text-toast">Incluye</h3><ul className="mt-6 space-y-3 text-cocoa/80"><li>✦ 14 módulos secuenciales de bolillo.</li><li>✦ Variantes especiales: arándano, nuez, romero, menta, ajo, cebolla e integral.</li><li>✦ Videos QR preparados por módulo.</li><li>✦ Fotografías técnicas preparadas.</li><li>✦ Manual maestro y recursos descargables vinculados.</li><li>✦ Boly™ como asistente educativo contextual.</li></ul></div></div><div className="mt-8"><BolyMessage tone="celebrate"><p>Premium no significa presión: significa más apoyo, más referencias y más tranquilidad para practicar.</p></BolyMessage></div></Section><Section eyebrow="Temario premium" title="Estructura completa del Curso Maestro de Bolillo"><Curriculum /></Section></>;
}
